services:
 hubService:
  image: selenium/hub:4.20

 chromeService:
  image: selenium/node-chrome:4.20
  shm_size: 2gb 
  depends_on: 
  - hubService
  deploy:
   replicas: 0
  env_file: .env 
 firefoxService:
  image: selenium/node-firefox:4.20
  shm_size: 2gb 
  depends_on:
  - hubService
  deploy:
   replicas: 0
  env_file: .env  

 edgeService:
  image: selenium/node-edge:4.20
  shm_size: 2gb 
  depends_on:
  - hubService
  deploy:
   replicas: 0
  env_file: .env  