services:
 vendorPortalService:
  image: christenajacoub82/selenium
  environment:
  - BROWSER=${BROWSER}
  - HUB_HOST=hubService
  - THREAD_COUNT=3
  - TEST_SUITE=vendor-portal.xml
  volumes:
  - ./output/vendor-portal:/home/selenium-docker/test-output

 flightReservationService:
  image: christenajacoub82/selenium
  environment:
  - BROWSER ### I can use it like this instead of using it BROWSER=${BROWSER}
  - HUB_HOST=hubService
  - THREAD_COUNT=3
  - TEST_SUITE=flight-reservation.xml
  volumes:
  - ./output/flight-reservation:/home/selenium-docker/test-output