services:
 testSuiteService:
  image: christenajacoub82/selenium
  environment:
  - BROWSER=${BROWSER}
  - HUB_HOST=hubService
  - THREAD_COUNT=3
  - TEST_SUITE=${TEST_SUITE}.xml
  - GRID_ENABLED=${GRID_ENABLED}
  - BROWSERSTACK_ENABLED=${BROWSERSTACK_ENABLED}
  volumes:
  - ./output/${TEST_SUITE}:/home/selenium-docker/test-output
